### ISSUE TITLE
ingestion-edge PubSub emulator cannot handle large requests

### ISSUE THREAD

**Issue by relud** [mozilla/gcp-ingestion#310]
publish operations bigger than 4194304 bytes when using PUBSUB_EMULATOR_HOST fail and hang indefinitely.

example:

```python
from google.cloud.pubsub_v1 import PublisherClient, types
client = PublisherClient()
topic = "projects/test/topics/topic"
client.create_topic(topic)
max_length_data = b"." * 4194266
too_long_data = b"." * 4194267
assert len(types.PublishRequest(topic=topic, messages=[{"data":max_length_data}]).SerializeToString()) == 4194304
assert len(types.PublishRequest(topic=topic, messages=[{"data":too_long_data}]).SerializeToString()) == 4194305
# works
client.api.publish(topic, [{"data":max_length_data}])
# hangs indefinitely with upstream emulator and our python emulator
client.api.publish(topic, [{"data":too_long_data}])
```

Google's java emulator spits out tracebacks like this one on that last line:

```
[pubsub] Dec 27, 2018 4:13:39 AM io.grpc.netty.NettyServerHandler onStreamError
[pubsub] WARNING: Stream Error
[pubsub] io.netty.handler.codec.http2.Http2Exception$StreamException: Received DATA frame for an unknown stream 27
[pubsub] 	at io.netty.handler.codec.http2.Http2Exception.streamError(Http2Exception.java:129)
[pubsub] 	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.shouldIgnoreHeadersOrDataFrame(DefaultHttp2ConnectionDecoder.java:535)
[pubsub] 	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:187)
[pubsub] 	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
[pubsub] 	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:421)
[pubsub] 	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:251)
[pubsub] 	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:160)
[pubsub] 	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
[pubsub] 	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:118)
[pubsub] 	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:383)
[pubsub] 	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:443)
[pubsub] 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[pubsub] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[pubsub] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[pubsub] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[pubsub] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[pubsub] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[pubsub] 	at io.gapi.emulators.netty.HttpVersionRoutingHandler.channelRead(HttpVersionRoutingHandler.java:103)
[pubsub] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[pubsub] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[pubsub] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[pubsub] 	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:241)
[pubsub] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[pubsub] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[pubsub] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[pubsub] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
[pubsub] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[pubsub] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[pubsub] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
[pubsub] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
[pubsub] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
[pubsub] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
[pubsub] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
[pubsub] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
[pubsub] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[pubsub] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[pubsub] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[pubsub] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by relud** [comment]
further testing suggests that the client is configured fine for this, but the emulator is not.
