### ISSUE TITLE
Decoder stopped progressing due to GC thrashing

### ISSUE THREAD

**Issue by jklukas** [mozilla/gcp-ingestion#374]
The decoder stopped making progress early this week, as noticed by @whd.  have been investigating and deploying different configurations to see if we can get past it.

There are two primary errors that I'm seeing. On workers, we see a few error-level messages about GC thrashing, causing the VM to terminate. On the shuffler, we're seeing deadline exceeded warnings:

> Rpc to decoder-gzip-klukas-11-01170620-iuru-harness-sgfh:12345 completed with error generic::deadline_exceeded: Deadline Exceeded

Google has a [Dataflow troubleshooting doc that mentions deadline exceeded errors](https://cloud.google.com/dataflow/docs/guides/troubleshooting-your-pipeline#tsg-rpc-timeout) that indicate this can be due to needing more workers, or insufficient disk space or disk throughput on the shuffler. I tried a few combinations of their suggestions for configuring more disk space, SSD-based disk, and additional workers, but no difference in behavior. The decoder fails to make progress.

I just deployed a new configuration with larger worker type `n1-standard-16` and this got us to a [new, more descriptive error about processing stuck in ParsePayload](https://console.cloud.google.com/logs/viewer?resource=dataflow_step%2Fjob_id%2F2019-01-17_06_20_33-18000127588288440561&logName=projects%2Fmoz-fx-data-beam-nonprod-b5f4%2Flogs%2Fdataflow.googleapis.com%252Fshuffler&logName=projects%2Fmoz-fx-data-beam-nonprod-b5f4%2Flogs%2Fdataflow.googleapis.com%252Fworker&interval=NO_LIMIT&project=moz-fx-data-beam-nonprod-b5f4&authuser=0&organizationId=442341870013&minLogLevel=400&expandAll=false&timestamp=2019-01-17T14%3A28%3A31.476000000Z&customFacets&limitCustomFacetWidth=true&scrollTimestamp=2019-01-17T14%3A27%3A30.693000000Z&dateRangeUnbound=forwardInTime&advancedFilter=resource.type%3D%22dataflow_step%22%0Aresource.labels.region%3D%22us-west1%22%0Aresource.labels.step_id%3D%22parsePayload%2FParMultiDo(DoFnWithErrors)%22%0Aresource.labels.job_name%3D%22decoder-gzip-klukas-11%22%0Aresource.labels.job_id%3D%222019-01-17_06_20_33-18000127588288440561%22%0Aresource.labels.project_id%3D%22moz-fx-data-beam-nonprod-b5f4%22%0Atimestamp%3D%222019-01-17T14%3A27%3A30.693000000Z%22%0AinsertId%3D%227912990887274951082%3A861052%3A0%3A277286%22) for more than 5 minutes. So current best theory is that there's a single record that causes pathological behavior in json parsing or validation.

<details>
Processing stuck in step parsePayload/ParMultiDo(DoFnWithErrors) for at least 05m14s without outputting or completing in state process at java.lang.Throwable.fillInStackTrace(Native Method) at java.lang.Throwable.fillInStackTrace(Throwable.java:783) at java.lang.Throwable.<init>(Throwable.java:265) at java.lang.Exception.<init>(Exception.java:66) at java.lang.RuntimeException.<init>(RuntimeException.java:62) at org.everit.json.schema.ValidationException.<init>(ValidationException.java:264) at org.everit.json.schema.ValidationException.<init>(ValidationException.java:288) at org.everit.json.schema.ValidationException.prepend(ValidationException.java:398) at org.everit.json.schema.ValidationException.prepend(ValidationException.java:378) at org.everit.json.schema.ValidationException.lambda$prepend$3(ValidationException.java:396) at org.everit.json.schema.ValidationException$$Lambda$412/60386056.apply(Unknown Source) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) at org.everit.json.schema.ValidationException.prepend(ValidationException.java:397) at org.everit.json.schema.ValidationException.prepend(ValidationException.java:378) at org.everit.json.schema.ValidationException.lambda$prepend$3(ValidationException.java:396) at org.everit.json.schema.ValidationException$$Lambda$412/60386056.apply(Unknown Source) at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1376) at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) at org.everit.json.schema.ValidationException.prepend(ValidationException.java:397) at org.everit.json.schema.ValidationException.prepend(ValidationException.java:378) at org.everit.json.schema.ObjectSchemaValidatingVisitor.visitPropertySchema(ObjectSchemaValidatingVisitor.java:159) at org.everit.json.schema.Visitor.visitObjectSchema(Visitor.java:131) at org.everit.json.schema.ObjectSchemaValidatingVisitor.visitObjectSchema(ObjectSchemaValidatingVisitor.java:35) at org.everit.json.schema.ObjectSchema.accept(ObjectSchema.java:266) at org.everit.json.schema.ValidatingVisitor.visitObjectSchema(ValidatingVisitor.java:113) at org.everit.json.schema.ObjectSchema.accept(ObjectSchema.java:266) at org.everit.json.schema.Visitor.visit(Visitor.java:43) at org.everit.json.schema.ValidatingVisitor.visit(ValidatingVisitor.java:30) at org.everit.json.schema.ValidatingVisitor.lambda$getFailureOfSchema$0(ValidatingVisitor.java:153) at org.everit.json.schema.ValidatingVisitor$$Lambda$354/264709280.run(Unknown Source) at org.everit.json.schema.ValidationFailureReporter.inContextOfSchema(ValidationFailureReporter.java:34) at org.everit.json.schema.CollectingFailureReporter.inContextOfSchema(CollectingFailureReporter.java:25) at org.everit.json.schema.ValidatingVisitor.getFailureOfSchema(ValidatingVisitor.java:153) at org.everit.json.schema.ObjectSchemaValidatingVisitor.visitPropertySchema(ObjectSchemaValidatingVisitor.java:157) at org.everit.json.schema.Visitor.visitObjectSchema(Visitor.java:131) at org.everit.json.schema.ObjectSchemaValidatingVisitor.visitObjectSchema(ObjectSchemaValidatingVisitor.java:35) at org.everit.json.schema.ObjectSchema.accept(ObjectSchema.java:266) at org.everit.json.schema.ValidatingVisitor.visitObjectSchema(ValidatingVisitor.java:113) at org.everit.json.schema.ObjectSchema.accept(ObjectSchema.java:266) at org.everit.json.schema.Visitor.visit(Visitor.java:43) at org.everit.json.schema.ValidatingVisitor.visit(ValidatingVisitor.java:30) at org.everit.json.schema.ValidatingVisitor.lambda$getFailureOfSchema$0(ValidatingVisitor.java:153) at org.everit.json.schema.ValidatingVisitor$$Lambda$354/264709280.run(Unknown Source) at org.everit.json.schema.ValidationFailureReporter.inContextOfSchema(ValidationFailureReporter.java:34) at org.everit.json.schema.CollectingFailureReporter.inContextOfSchema(CollectingFailureReporter.java:25) at org.everit.json.schema.ValidatingVisitor.getFailureOfSchema(ValidatingVisitor.java:153) at org.everit.json.schema.ObjectSchemaValidatingVisitor.visitPropertySchema(ObjectSchemaValidatingVisitor.java:157) at org.everit.json.schema.Visitor.visitObjectSchema(Visitor.java:131) at org.everit.json.schema.ObjectSchemaValidatingVisitor.visitObjectSchema(ObjectSchemaValidatingVisitor.java:35) at org.everit.json.schema.ObjectSchema.accept(ObjectSchema.java:266) at org.everit.json.schema.ValidatingVisitor.visitObjectSchema(ValidatingVisitor.java:113) at org.everit.json.schema.ObjectSchema.accept(ObjectSchema.java:266) at org.everit.json.schema.Visitor.visit(Visitor.java:43) at org.everit.json.schema.ValidatingVisitor.visit(ValidatingVisitor.java:30) at org.everit.json.schema.ValidatingVisitor.lambda$getFailureOfSchema$0(ValidatingVisitor.java:153) at org.everit.json.schema.ValidatingVisitor$$Lambda$354/264709280.run(Unknown Source) at org.everit.json.schema.ValidationFailureReporter.inContextOfSchema(ValidationFailureReporter.java:34) at org.everit.json.schema.CollectingFailureReporter.inContextOfSchema(CollectingFailureReporter.java:25) at org.everit.json.schema.ValidatingVisitor.getFailureOfSchema(ValidatingVisitor.java:153) at org.everit.json.schema.ObjectSchemaValidatingVisitor.visitPropertySchema(ObjectSchemaValidatingVisitor.java:157) at org.everit.json.schema.Visitor.visitObjectSchema(Visitor.java:131) at org.everit.json.schema.ObjectSchemaValidatingVisitor.visitObjectSchema(ObjectSchemaValidatingVisitor.java:35) at org.everit.json.schema.ObjectSchema.accept(ObjectSchema.java:266) at org.everit.json.schema.ValidatingVisitor.visitObjectSchema(ValidatingVisitor.java:113) at org.everit.json.schema.ObjectSchema.accept(ObjectSchema.java:266) at org.everit.json.schema.Visitor.visit(Visitor.java:43) at org.everit.json.schema.ValidatingVisitor.visit(ValidatingVisitor.java:30) at org.everit.json.schema.DefaultValidator.performValidation(Validator.java:53) at org.everit.json.schema.Schema.validate(Schema.java:126) at com.mozilla.telemetry.decoder.ParsePayload.processElement(ParsePayload.java:146) at com.mozilla.telemetry.decoder.ParsePayload.processElement(ParsePayload.java:30) at com.mozilla.telemetry.transforms.MapElementsWithErrors$DoFnWithErrors.processElementOrError(MapElementsWithErrors.java:88) at com.mozilla.telemetry.transforms.MapElementsWithErrors$DoFnWithErrors$DoFnInvoker.invokeProcessElement(Unknown Source)
</details>

**Comment by jklukas** [comment]
I deployed the changes proposed in #375 and it looks like failing early in validation solved the problem. Decoder is actually processing messages and system lag is slowly decreasing.
